# Site settings
title: Different Games Collective
description: > # this means to ignore newlines until "baseurl:"
  Different Games Collective creates community resources and events to support
  marginalized voices in DIY and independent games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.differentgames.org" # the base hostname & protocol for your site
twitter_username: differentgames
tumblr_username: differentgamescollective

# Build settings
markdown: kramdown
exclude:
  - vendor
  - deploy.sh
  - README.md
  - circle.yml
  - Gemfile
  - Gemfile.lock

collections:
  nav_pages:
    output: true
